packages:
- '.'
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 60c8daadacaef620865ca174c0f5c46607b5aab8
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
  extra-dep: True
extra-deps: []
resolver: lts-12.0
allow-newer: true
