packages:
- '.'
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 839c7e00a7f48b33f13b7ce7914e713e4e2261ad
- location:
    git: https://github.com/lamdu/freetype2
    commit: b6b3f82b9f8acb925d8f36ecc1520832ad256444
extra-deps: []
resolver: lts-5.12
