packages:
- '.'
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: a6d46d2ce7534c85949d23be7a2766fa103e00aa
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
  extra-dep: True
extra-deps: []
resolver: lts-7.14
