packages:
- '.'
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 57b9f17dca65521824dc4bdb821dc014f622ecad
- location:
    git: https://github.com/lamdu/freetype2
    commit: b6b3f82b9f8acb925d8f36ecc1520832ad256444
extra-deps: []
resolver: lts-5.12
