packages:
- '.'
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 2151343a2a26031326d0ccfca65a69975b20b9f8
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
  extra-dep: True
extra-deps: []
resolver: lts-7.14
