packages:
- '.'
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 3407e0ecafabb3ad854a44be815d830c7ded36a9
- location:
    git: https://github.com/lamdu/freetype2
    commit: b6b3f82b9f8acb925d8f36ecc1520832ad256444
extra-deps: []
resolver: lts-5.12
