packages:
- '.'
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 60c8daadacaef620865ca174c0f5c46607b5aab8
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 520351a6e1cf5b18edae45d0e4a20758211fa8da
  extra-dep: True
extra-deps: []
resolver: lts-12.17
allow-newer: true
