packages:
- '.'

extra-deps:
- github: lamdu/bindings-freetype-gl
  commit: abcb891cf2ed01edb2d02197ef2b354d6ff43db5
- github: lamdu/freetype2
  commit: 046328d92312d65638440132c016a3081d9c32a4

resolver: lts-17.10

allow-newer: true
