packages:
- '.'
- '../bindings-freetype-gl'
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
  extra-dep: True
extra-deps: []
resolver: lts-7.14
